### ISSUE TITLE
Screenshots can't be fired since 1.6

### ISSUE THREAD

**Issue by howie-f** [xbmc/Official-Kodi-Remote-iOS#162]
i added a user action "screenshot" to my remote, nice feature for bug-reports or pr descriptions.

That doesn't work anymore (since version 1.6), no screenshot is saved to the kodi folder.
after a tip on the action i get **Dies ist nicht möglich** (this isn't possible)

while pressing "**Aktion ausführen**" (execute action) in screenshot 2 does what it should:

![IMG_3814](https://user-images.githubusercontent.com/58829855/107547198-79bf9b00-6bcd-11eb-873c-e94a21469225.PNG)
![IMG_3815](https://user-images.githubusercontent.com/58829855/107547378-a8d60c80-6bcd-11eb-8a49-f23c0fb8501f.PNG)

**Comment by wutschel** [comment]
Confirmed.

**Comment by wutschel** [comment]
Nice bug. Was caused by the recently updated German translation and impact *all* action buttons. It is important to use different localized strings for "Add button" and "Add action button". This is now fixed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/160.

**Comment by howie-f** [comment]
sometimes surprised what all can have impact. thanks for the quick fix 👍

**Comment by howie-f** [comment]
hm, is the fix for this included in testflight rel. 2051 ? it still doesn‘t work here with the same error message

**Comment by kambala-decapitator** [comment]
yes, it's included.

reopening the issue then.

**Comment by wutschel** [comment]
I just tested with current testflight version (1.6.1 build 2054) on iPhone XS with iOS 14.4. It works.

But: You need to make sure you freshly add the action button. The issue happened while creation, not while using an already existing action button.

**Comment by howie-f** [comment]
exactly like this @wutschel , thanks for the hint
